language: node_js
node_js:
- 10.16.0
branches:
  only:
  - production
cache:
  npm: true
before_install:
- openssl aes-256-cbc -K $encrypted_696db3aea73e_key -iv $encrypted_696db3aea73e_iv
  -in secret.json.enc -out secret.json -d
install:
- npm i
deploy:
  provider: script
  skip_cleanup: true
  script: npm run publish
  on: production
